export const telefoni = [
  {
    id: 1,
    youtube:
      '<iframe width="560" height="315" src="https://www.youtube.com/embed/s5QWeYVQxD8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    proizvodjac: "Samsung",
    model: "Galaxy S20 Plus",
    prednja: "samsung tel/1Samsung_Galaxy_S20_Ultra_Cloud_White_Front.jpg.jpg",
    zadnja:
      "samsung tel/1NazadSamsung_Galaxy_S20_Ultra_Cloud_White_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Plava", "Siva", "Crna"],
    ekran: "6.7inča",
    cena: 740,
    ram: "8GB",
    kapacitet: "128GB",
    mreza: "4G,5G",
    baterija: "4500mAh,",
    kamera: "64Mpx",
  },
  {
    id: 2,
    youtube:
      '<iframe width="560" height="315" src="https://www.youtube.com/embed/Z4mirR9b1cI" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    proizvodjac: "Samsung",
    model: "Galaxy A30s",
    prednja: "samsung tel/samsung2.jpg",
    zadnja: "samsung tel/samsung2Nazad.jpg",
    sim: "dual",
    boja: ["Crna", "Plava", "Zelena", "Bela"],
    ekran: "6.4 inča",
    cena: 222,
    ram: "4GB",
    kapacitet: "64GB",
    mreza: "4G",
    baterija: "4000mAh",
    kamera: "25Mpx",
  },
  {
    id: 3,
    youtube:
      '<iframe width="560" height="315" src="https://www.youtube.com/embed/ZkTM4htgZCo" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    proizvodjac: "Samsung",
    model: "Galaxy A20e",
    prednja: "samsung tel/3Samsung_Galaxy_A20e_Black_Front.jpg.jpg",
    zadnja: "samsung tel/3NazadSamsung_Galaxy_A20e_Black_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Crna", "Bela"],
    ekran: "5,8 inča",
    cena: 149,
    ram: "3GB",
    kapacitet: "32GB",
    mreza: "4G",
    baterija: "3000mAh",
    kamera: "13Mpx",
  },
  {
    id: 4,
    youtube:
      '<iframe width="560" height="315" src="https://www.youtube.com/embed/9jsHOJtPNjs" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    proizvodjac: "Samsung",
    model: "Galaxy A21s",
    prednja: "samsung tel/4Samsung_Galaxy_A21s_Black_Front.jpg.jpg",
    zadnja: "samsung tel/4NazadSamsung_Galaxy_A21s_Black_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Crna", "Plava", "Bela"],
    ekran: "6,5 inča",
    cena: 180,
    ram: "3GB",
    kapacitet: "32GB",
    mreza: "4G",
    baterija: "5000mAh",
    kamera: "48Mpx",
  },
  {
    id: 5,
    youtube:
      '<iframe width="560" height="315" src="https://www.youtube.com/embed/V7VWcJgRA0g" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    proizvodjac: "Samsung",
    model: "Galaxy S20 Ultra",
    prednja: "samsung tel/5Samsung_Galaxy_S20_Ultra_Cloud_White_Front.jpg.jpg",
    zadnja:
      "samsung tel/5NazadSamsung_Galaxy_S20_Ultra_Cloud_White_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Siva", "Crna"],
    ekran: "6,9 inča",
    cena: 1000,
    ram: "12GB",
    kapacitet: "128GB",
    mreza: "4G,5G",
    baterija: "5000mAh",
    kamera: "64Mpx",
  },
  {
    id: 6,
    youtube:
      '<iframe width="560" height="315" src="https://www.youtube.com/embed/M4DUy9fkRj0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    proizvodjac: "Samsung",
    model: "Galaxy S20 Plus",
    prednja: "samsung tel/6Samsung_Galaxy_S20_Plus_Aura_Blue_Front.jpg.jpg",
    zadnja: "samsung tel/6NazadSamsung_Galaxy_S20_Plus_Aura_Blue_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Plava", "Siva", "Crna"],
    ekran: "6.7 inča",
    cena: 740,
    ram: "8GB",
    kapacitet: "128GB",
    mreza: "4G,5G",
    baterija: "4500mAh,",
    kamera: "64Mpx",
  },
  {
    id: 7,
    youtube:
      '<iframe width="560" height="315" src="https://www.youtube.com/embed/7YDjMHyzrho" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    proizvodjac: "Samsung",
    model: "Galaxy S10 Lite",
    prednja: "samsung tel/7Samsung_Galaxy_S10_Lite_Prism_Blue_Front.jpg.jpg",
    zadnja: "samsung tel/7NazadSamsung_Galaxy_S10_Lite_Prism_Blue_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Bela", "Crna", "Plava"],
    ekran: "6.7 inča",
    cena: 450,
    ram: "6GB",
    kapacitet: "128GB",
    mreza: "4G,5G",
    baterija: "4500mAh",
    kamera: "48Mpx",
  },
  {
    id: 8,
    youtube:
      '<iframe width="560" height="315" src="https://www.youtube.com/embed/Gzy_nCkn88U" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    proizvodjac: "Samsung",
    model: "Galaxy S9 Plus",
    prednja: "samsung tel/8Samsung_Galaxy_S9_Plus_Black_Front.jpg.jpg",
    zadnja: "samsung tel/8NazadSamsung_Galaxy_S9_Plus_Black_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Crna", "Plava", "Siva", "Ljubičasta", "Crvena", "Zlatna"],
    ekran: "6.2 inča",
    cena: 440,
    ram: "6GB",
    kapacitet: "64GB",
    mreza: "4G",
    baterija: "3500AH",
    kamera: "12Mpx",
  },
  {
    id: 9,
    youtube: "",
    proizvodjac: "Samsung",
    model: "Galaxy A30s",
    prednja: "samsung tel/9Samsung_Galaxy_A30s_Prism_Crush_Bleck_Front.jpg.jpg",
    zadnja:
      "samsung tel/9NazadSamsung_Galaxy_A30s_Prism_Crush_Bleck_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Crna", "Plava", "Zelena", "Bela"],
    ekran: "6.4 inča",
    cena: 210,
    ram: "4GB",
    kapacitet: "64GB",
    mreza: "4G",
    baterija: "4000mAh",
    kamera: "25Mpx",
  },
  {
    id: 10,
    youtube: "",
    proizvodjac: "Samsung",
    model: "Galaxy A51",
    prednja: "samsung tel/10Samsung_Galaxy_A51_Black_Front.jpg.jpg",
    zadnja: "samsung tel/10NazadSamsung_Galaxy_A51_Black_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Crna", "Plava", "Bela", "Roze", "Multikolorna"],
    ekran: "6.5 inča",
    cena: 299,
    ram: "4GB",
    kapacitet: "128GB",
    mreza: "4G",
    baterija: "4000mAh",
    kamera: "48Mpx",
  },
  {
    id: 11,
    youtube: "",
    proizvodjac: "Samsung",
    model: "Galaxy A71",
    prednja: "samsung tel/11Samsung_Galaxy_A71_Black_Front.jpg.jpg",
    zadnja: "samsung tel/11NazadSamsung_Galaxy_A71_Black_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Crna", "Multikolorna", "Srebrna", "Plava", "Roze"],
    ekran: "6.7 inča",
    cena: 375,
    ram: "6GB",
    kapacitet: "128GB",
    mreza: "4G",
    baterija: "4500mAh",
    kamera: "64Mpx",
  },
  {
    id: 12,
    youtube: "",
    proizvodjac: "Samsung",
    model: "Galaxy A50",
    prednja: "samsung tel/12Samsung_Galaxy_A51_Black_Front.jpg.jpg",
    zadnja: "samsung tel/12NazadSamsung_Galaxy_A51_Black_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Crna", "Plava", "Bela", "Roze"],
    ekran: "5,5 inča",
    cena: 325,
    ram: "4GB",
    kapacitet: "228GB",
    mreza: "4G",
    baterija: "4000mAh",
    kamera: "25Mpx",
  },
  {
    id: 13,
    youtube: "",
    proizvodjac: "Samsung",
    model: "Galaxy Note 10 Lite",
    prednja:
      "samsung tel/13Samsung_Galaxy_Note_10_Lite_Aura_Black_Front.jpg.jpg",
    zadnja:
      "samsung tel/13NazadSamsung_Galaxy_Note_10_Lite_Aura_Black_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Bela", "Crna", "Crvena"],
    ekran: "6.7 inča",
    cena: 429,
    ram: "6GB",
    kapacitet: "128GB",
    mreza: "4G",
    baterija: "4500mAh",
    kamera: "32Mpx",
  },
  {
    id: 14,
    youtube: "",
    proizvodjac: "Samsung",
    model: "Galaxy A41",
    prednja: "samsung tel/14Samsung_Galaxy_A41_Black_Front.jpg.jpg",
    zadnja: "samsung tel/14NazadSamsung_Galaxy_A41_Black_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Crna", "Srebrna", "Plava", "Crvena"],
    ekran: "6.1 inča",
    cena: 275,
    ram: "4GB",
    kapacitet: "64GB",
    mreza: "4G",
    baterija: "3500mAh",
    kamera: "48Mpx",
  },
  {
    id: 15,
    youtube: "",
    proizvodjac: "Samsung",
    model: "Galaxy A10s",
    prednja: "samsung tel/15Samsung_Galaxy_A10s_Blue_Front.jpg.jpg",
    zadnja: "samsung tel/15NazadSamsung_Galaxy_A10s_Blue_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Crna", "Plava", "Crvena", "Zelena"],
    ekran: "6.2 inča",
    cena: 135,
    ram: "2GB",
    kapacitet: "32GB",
    mreza: "4G",
    baterija: "4000mAh",
    kamera: "13Mpx",
  },
  {
    id: 16,
    youtube: "",
    proizvodjac: "Apple",
    model: "iPhone 11",
    prednja: "apple/16Apple_iPhone_11_Red_Front.jpg.jpg",
    zadnja: "apple/16NazadApple_iPhone_11_Red_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Crna", "Zelena", "Žuta", "Ljubičasta", "Crvena", "Bela"],
    ekran: "6.1 inča",
    cena: 755,
    ram: "4GB",
    kapacitet: "64GB",
    mreza: "4G",
    baterija: "3110mAh",
    kamera: "13Mpx",
  },
  {
    id: 17,
    youtube: "",
    proizvodjac: "Apple",
    model: "iPhone 11 Pro Max",
    prednja: "apple/17Apple_iPhone_11_Pro-Max_Green_Front.jpg.jpg",
    zadnja: "apple/17NazadApple_iPhone_11_Pro-Max_Green_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Zelena", "Siva", "Srebrna", "Zlatna"],
    ekran: "6.5 inča",
    cena: 1189,
    ram: "4GB",
    kapacitet: "64GB",
    mreza: "4G",
    baterija: "3969mAh",
    kamera: "12Mpx",
  },
  {
    id: 18,
    youtube: "",
    proizvodjac: "Apple",
    model: "iPhone XR",
    prednja: "apple/18Apple_iPhone_XR_Black_Front.jpg_tn.jpg",
    zadnja: "apple/18NazadApple_iPhone_XR_Black_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Crna", "Crvena", "Žuta", "Plava", "Roze"],
    ekran: "6.1 inča",
    cena: 590,
    ram: "3GB",
    kapacitet: "64GB",
    mreza: "4G",
    baterija: "2942mAh",
    kamera: "12Mpx",
  },
  {
    id: 19,
    youtube: "",
    proizvodjac: "Apple",
    model: "iPhone 11",
    prednja: "apple/19Apple_iPhone_11_Black_Front.jpg.jpg",
    zadnja: "apple/19NazadApple_iPhone_11_Black_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Crna", "Zelena", "Žuta", "Ljubičasta", "Crvena", "Bela"],
    ekran: "6.1 inča",
    cena: 755,
    ram: "4GB",
    kapacitet: "128GB",
    mreza: "4G",
    baterija: "3110mAh",
    kamera: "13Mpx",
  },
  {
    id: 20,
    youtube: "",
    proizvodjac: "Apple",
    model: "iPhone SE",
    prednja: "./apple/123iphone-se-red-front__82446.1587414033.webp",
    zadnja: './apple/223iphone+SE.png',
    sim: "dual",
    boja: ["Crna", "Bela", "Roze"],
    ekran: "6.2 inča",
    cena: 445,
    ram: "2GB",
    kapacitet: "32GB",
    mreza: "4G",
    baterija: "4000mAh",
    kamera: "13Mpx",
  },
  {
    id: 21,
    youtube: "",
    proizvodjac: "Apple",
    model: "Watch Series 5",
    prednja:
      "apple/21Watch_Apple_Watch_Series_5_Aluminium_Case_Grey_Sport_Band_Black_Front.jpg.jpg",
    zadnja:
      "apple/21Watch_Apple_Watch_Series_5_GPS_+_Cellular_Aluminium_Case_Grey_Sport_Band_Black_Front_Side.jpg.jpg",
    boja: ["Crna", "Bela", "Crvena", "Roze"],
    ekran: "1.7 inča",
    cena: 465,
    kapacitet: "32GB",
  },
  {
    id: 22,
    youtube: "",
    proizvodjac: "Apple",
    model: "iPhone 6s",
    prednja: "apple/22Apple_iPhone_6s_Grey_Fron.jpg.jpg",
    zadnja: "apple/22NazadApple_iPhone_6s_Grey_Rea.jpg.jpg",
    sim: "dual",
    boja: ["Siva", "Srebrna", "Zlatna"],
    ekran: "6.2 inča",
    cena: 270,
    ram: "2GB",
    kapacitet: "32GB",
    mreza: "4G",
    baterija: "1715mAh",
    kamera: "12Mpx",
  },
  {
    id: 23,
    youtube: "",
    proizvodjac: "Apple",
    model: "iPhone XR",
    prednja: "apple/23Apple_iPhone_XR_Red_Front.jpg.jpg",
    zadnja: 'apple/23NazadApple_iPhone_XR_Red_Rear.jpg.jpg"',
    sim: "dual",
    boja: ["Crna", "Crvena", "Žuta", "Plava", "Roze"],
    ekran: "6.1 inča",
    cena: 599,
    ram: "3GB",
    kapacitet: "64GB",
    mreza: "4G",
    baterija: "2942mAh",
    kamera: "12Mpx",
  },
  {
    id: 24,
    youtube: "",
    proizvodjac: "Apple",
    model: "iPhone SE",
    prednja: "apple/24Apple_iPhone_SE_(2020)_White_Front.jpg_tn.jpg",
    zadnja: "apple/24NazadApple_iPhone_SE_(2020)_White_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Crna", "Bela", "Crvena"],
    ekran: "4.7 inča",
    cena: 445,
    ram: "3GB",
    kapacitet: "64GB",
    mreza: "4G",
    baterija: "1821mAh",
    kamera: "12Mpx",
  },
  {
    id: 25,
    youtube: "",
    proizvodjac: "Apple",
    model: "Watch Series 3",
    prednja:
      "apple/25Apple_Watch_Series_3_Sport_Silver_Aluminum_Case_with_Fog_Sport_Band_Front.jpg.jpg",
    zadnja:
      "apple/25NazadApple_Watch_Series_3_Sport_Silver_Aluminum_Case_with_Fog_Sport_Band_Front_Side.jpg.jpg",
    boja: ["Crna", "Bela"],
    ekran: "1.6 inča",
    cena: 235,
    ram: "6GB",
    kapacitet: "16GB",
    mreza: "4G",
  },
  {
    id: 26,
    youtube: "",
    proizvodjac: "Apple",
    model: "AirPods",
    prednja: "apple/26Apple_AirPods_(2019)_White_Front.jpg.jpg",
    zadnja:
      "apple/26NazadApple_AirPods_(2019)_Wireless_Charging_case_White_Front_Opened.jpeg.jpg",
    boja: ["Crna", "Bele"],
  },

  {
    id: 27,
    youtube: "",
    proizvodjac: "Apple",
    model: "iPad 10.2",
    prednja: "apple/27Apple_iPad_10-2_(2019)_Gold_Front.jpg.jpg",
    zadnja: "apple/27NazadApple_iPad_10-2_(2019)_Gold_WiFi_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Crna", "Bela"],
    ekran: "10.2 inča",
    cena: 370,
    ram: "2GB",
    kapacitet: "32GB",
    mreza: "4G",
    baterija: "4000mAh",
    kamera: "8Mpx",
  },
  {
    id: 28,
    youtube: "",
    proizvodjac: "Apple",
    model: "iPhone 7",
    prednja: "apple/28Apple_iPhone_7_Plus_Black_Front.jpg.jpg",
    zadnja: "apple/28NazadApple_iPhone_7_Plus_Black_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Crna", "Plava", "Crvena", "Zelena"],
    ekran: "4.7 inča",
    cena: 500,
    ram: "2GB",
    kapacitet: "32GB",
    mreza: "4G",
    baterija: "4000mAh",
    kamera: "12Mpx",
  },
  {
    id: 29,
    youtube: "",
    proizvodjac: "Apple",
    model: "iPhone X",
    prednja: "apple/29Apple_iPhone_X_Space_Grey_Front.jpg.jpg",
    zadnja: 'apple/29NazadApple_iPhone_X_Space_Grey_Rear.jpg.jpg"',
    sim: "dual",
    boja: ["Siva", "Srebrna"],
    ekran: "5.8 inča",
    cena: 550,
    ram: "3GB",
    kapacitet: "64GB",
    mreza: "4G",
    baterija: "2716mAh",
    kamera: "12Mpx",
  },
  {
    id: 30,
    youtube: "",
    proizvodjac: "Apple",
    model: "iPad Pro 11",
    prednja: "apple/30Apple_iPad_Pro_11_Space_Grey_Front.jpg.jpg",
    zadnja: "apple/30NazadApple_iPad_Pro_11_Space_Grey_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Crna", "Bela"],
    ekran: "12.2 inča",
    cena: 1200,
    ram: "6GB",
    kapacitet: "1TB",
    mreza: "4G",
    baterija: "7812mAh",
    kamera: "12Mpx",
  },
  {
    id: 31,
    youtube: "",
    proizvodjac: "Huawei",
    model: "P40 Lite",
    prednja: "huawei/31Huawei_P40_Lite_Black_Front.jpg.jpg",
    zadnja: "huawei/31NazadHuawei_P40_Lite_Black_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Crna", "Bela"],
    ekran: "6.4 inča",
    cena: 220,
    ram: "6GB",
    kapacitet: "128GB",
    mreza: "4G",
    baterija: "4200mAh",
    kamera: "48Mpx",
  },
  {
    id: 32,
    youtube: "",
    proizvodjac: "Huawei",
    model: "P40 Lite E",
    prednja: "huawei/32Huawei_P40_Lite_E_Black_Front.jpg.jpg",
    zadnja: "huawei/32NazadHuawei_P40_Lite_E_Black_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Crna", "Plava"],
    ekran: "6.39 inča",
    cena: 165,
    ram: "4GB",
    kapacitet: "64GB",
    mreza: "4G",
    baterija: "4000mAh",
    kamera: "12Mpx",
  },
  {
    id: 33,
    youtube: "",
    proizvodjac: "Huawei",
    model: "Y7",
    prednja: "huawei/33Huawei_Y7_(2019)_Black_Front.jpg.jpg",
    zadnja: "huawei/33NazadHuawei_Y7_(2019)_Black_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Crna", "Plava", "Crvena"],
    ekran: "6.26 inča",
    cena: 152,
    ram: "3GB",
    kapacitet: "32GB",
    mreza: "4G",
    baterija: "4000mAh",
    kamera: "13Mpx",
  },
  {
    id: 34,
    youtube: "",
    proizvodjac: "Huawei",
    model: "P30 Lite",
    prednja: "huawei/34Huawei_P30_Lite_White_Front.jpg_tn.jpg",
    zadnja: "huawei/34NazadHuawei_P30_Lite_White_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Crna", "Bela"],
    ekran: "6.4 inča",
    cena: 220,
    ram: "6GB",
    kapacitet: "128GB",
    mreza: "4G",
    baterija: "4200mAh",
    kamera: "48Mpx",
  },
  {
    id: 35,
    youtube: "",
    proizvodjac: "Huawei",
    model: "Nova 5T",
    prednja: "huawei/35Huawei_Nova_5T_Black_Front.jpg.jpg",
    zadnja: "huawei/35NazadHuawei_Nova_5T_Black_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Crna", "Ljubičasta", "Plava"],
    ekran: "6.26 inča",
    cena: 299,
    ram: "6GB",
    kapacitet: "128GB",
    mreza: "4G",
    baterija: "3750mAh",
    kamera: "48Mpx",
  },
  {
    id: 36,
    youtube: "",
    proizvodjac: "Huawei",
    model: "P Smart Z",
    prednja: "huawei/36Huawei_P_Smart_Z_Black_Front.jpg.jpg",
    zadnja: "huawei/36NazadHuawei_P_Smart_Z_Black_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Crna", "Zelena", "Plava"],
    ekran: "6.59 inča",
    cena: 185,
    ram: "4GB",
    kapacitet: "64GB",
    mreza: "4G",
    baterija: "4000mAh",
    kamera: "16Mpx",
  },
  {
    id: 37,
    youtube: "",
    proizvodjac: "Huawei",
    model: "Y5p",
    prednja: "huawei/37Huawei_Y5p_Mint_Green_Front.jpg.jpg",
    zadnja: "huawei/37NazadHuawei_Y5p_Mint_Green_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Crna", "Zelena", "Plava"],
    ekran: "5.45 inča",
    cena: 99,
    ram: "2GB",
    kapacitet: "32GB",
    mreza: "4G",
    baterija: "3020mAh",
    kamera: "8Mpx",
  },
  {
    id: 38,
    youtube: "",
    proizvodjac: "Huawei",
    model: "P30 Pro",
    prednja: "huawei/38Huawei_P30_Pro_Black_Front.jpg.jpg",
    zadnja: "huawei/38NazadHuawei_P30_Pro_Black_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Multikolorna", "Orange", "Crna", "Bela"],
    ekran: "6.47 inča",
    cena: 550,
    ram: "6GB",
    kapacitet: "128GB",
    mreza: "4G",
    baterija: "4200mAh",
    kamera: "40Mpx",
  },
  {
    id: 39,
    youtube: "",
    proizvodjac: "Huawei",
    model: "P40 5G",
    prednja: "huawei/39Huawei_P40_Gold_Front.jpg.jpg",
    zadnja: "huawei/39NazadHuawei_P40_Gold_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Zlatna", "Plava", "Bela", "Crna"],
    ekran: "6.58 inča",
    cena: 850,
    ram: "8GB",
    kapacitet: "128GB",
    mreza: "5G",
    baterija: "4200mAh",
    kamera: "40Mpx",
  },
  {
    id: 40,
    youtube: "",
    proizvodjac: "Huawei",
    model: "P Smart LTE",
    prednja: "huawei/40Huawei_P_Smart_Blue_Front.jpg.jpg",
    zadnja: "huawei/40NazadHuawei_P_Smart_Blue_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Plava", "Zlatna", "Crna"],
    ekran: "5.65 inča",
    cena: 154,
    ram: "3GB",
    kapacitet: "32GB",
    mreza: "4G",
    baterija: "3000mAh",
    kamera: "13Mpx",
  },
  {
    id: 41,
    youtube: "",
    proizvodjac: "Huawei",
    model: "Watch GT 2",
    prednja: "huawei/42Huawei_Watch_GT_2_Sport_Night_Black_Front.jpg.jpg",
    zadnja:
      "huawei/42 NazadHuawei_Watch_GT_2_Sport_Night_Black_Rear_Side.jpg.jpg",
    sim: "dual",
    boja: ["Crna", "Bela"],
    cena: 200,
    ram: "4GB",
  },
  {
    id: 42,
    youtube: "",
    proizvodjac: "Xiaomi",
    model: "Redmi Note 9 Pro",
    prednja: "xiaomi/43Xiaomi_Redmi_Note_9_Pro_Grey_Front.jpg.jpg",
    zadnja: "xiaomi/43NazadXiaomi_Redmi_Note_9_Pro_Grey_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Zelena", "Bela", "Siva"],
    ekran: "6.67 inča",
    cena: 240,
    ram: "6GB",
    kapacitet: "64GB",
    mreza: "4G",
    baterija: "5020mAh",
    kamera: "64Mpx",
  },
  {
    id: 43,
    youtube: "",
    proizvodjac: "Xiaomi",
    model: "Redmi Note 8 Pro",
    prednja: "xiaomi/44Xiaomi_Redmi_Note_8_Pro_Deep_Sea_Blue_Front.jpg.jpg",
    zadnja: "xiaomi/44NazadXiaomi_Redmi_Note_8_Pro_Deep_Sea_Blue_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Crna", "Plava", "Crvena", "Bela"],
    ekran: "6.53 inča",
    cena: 205,
    ram: "6GB",
    kapacitet: "64GB",
    mreza: "4G",
    baterija: "4500mAh",
    kamera: "64Mpx",
  },
  {
    id: 44,
    youtube: "",
    proizvodjac: "Xiaomi",
    model: "Redmi Note 8",
    prednja: "xiaomi/45Xiaomi_Redmi_Note_8_Grey_Front.jpg.jpg",
    zadnja: "xiaomi/45NazadXiaomi_Redmi_Note_8_Grey_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Crna", "Plava", "Bela", "Zelena"],
    ekran: "6.3 inča",
    cena: 169,
    ram: "4GB",
    kapacitet: "64GB",
    mreza: "4G",
    baterija: "4000mAh",
    kamera: "48Mpx",
  },
  {
    id: 45,
    youtube: "",
    proizvodjac: "Xiaomi",
    model: "Redmi Note 9",
    prednja: "xiaomi/46Xiaomi_Redmi_Note_9_Pro_White_Front.jpg.jpg",
    zadnja: "xiaomi/46NazadXiaomi_Redmi_Note_9_Pro_White_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Bela", "Siva", "Zelena"],
    ekran: "6.67 inča",
    cena: 275,
    ram: "6GB",
    kapacitet: "128GB",
    mreza: "4G",
    baterija: "4000mAh",
    kamera: "64Mpx",
  },
  {
    id: 46,
    youtube: "",
    proizvodjac: "Xiaomi",
    model: "Mi Note 10",
    prednja: "xiaomi/47Xiaomi_Mi_Note-Pro_10_Black_Front.jpg.jpg",
    zadnja: "xiaomi/47NazadXiaomi_Mi_Note-Pro_10_Black_Rear.jpg",
    sim: "dual",
    boja: ["Crna", "Bela", "Zelena"],
    ekran: "6.47 inča",
    cena: 409,
    ram: "6GB",
    kapacitet: "128GB",
    mreza: "4G",
    baterija: "5260mAh",
    kamera: "108Mpx,",
  },
  {
    id: 47,
    youtube: "",
    proizvodjac: "Xiaomi",
    model: "Poco F2 Pro",
    prednja: "xiaomi/48Xiaomi_Poco_F2_Pro_Grey_Front_Side.jpg.jpg",
    zadnja: "xiaomi/48NazadXiaomi_Poco_F2_Pro_Grey_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Ljubicasta", "Plava", "Bela", "Siva"],
    ekran: "6.67 inča",
    cena: 405,
    ram: "6GB",
    kapacitet: "128GB",
    mreza: "5G",
    baterija: "4700mAh",
    kamera: "64Mpx",
  },
  {
    id: 48,
    youtube: "",
    proizvodjac: "Xiaomi",
    model: "Mi 10",
    prednja: "xiaomi/49Xiaomi_Mi_10_5G_Twilight_Grey_Front.jpg.jpg",
    zadnja: "xiaomi/49NazadXiaomi_Mi_10_5G_Twilight_Grey_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Srebrna", "Plava", "Zlatna"],
    ekran: "6.67 inča",
    cena: 550,
    ram: "8GB",
    kapacitet: "128GB",
    mreza: "5G",
    baterija: "4780mAh",
    kamera: "108Mpx",
  },
  {
    id: 49,
    youtube: "",
    proizvodjac: "Xiaomi",
    model: "Mi 9T Pro",
    prednja: "xiaomi/50Xiaomi_Mi_9T_Pro_Glacier_Blue_Fornt.jpg.jpg",
    zadnja: "xiaomi/50NazadXiaomi_Mi_9T_Pro_Glacier_Blue_Rear.jpg.jpg",
    sim: "dual",
    boja: ["Crna", "Plava", "Crvena", "Bela"],
    ekran: "6.39 inča",
    cena: 600,
    ram: "6GB",
    kapacitet: "64GB",
    mreza: "4G",
    baterija: "4000mAh",
    kamera: "48Mpx",
  },
];
