let header = document.createElement("header");
header.id = "header";
export let logo = document.createElement("div");
logo.id = "divLog";

export let elementsNav = document.createElement("a");
elementsNav.classList.add("icon");
logo.appendChild(elementsNav);
export let iNav = document.createElement("p");
iNav.classList.add("burger");
elementsNav.appendChild(iNav);

export let link = document.createElement("a");
link.innerText = "LogIn";
link.classList.add("logIN");
logo.appendChild(link);
header.appendChild(logo);
document.body.appendChild(header);
let headerTop = document.createElement("div");
headerTop.id = "header-top";
header.appendChild(headerTop);
export let divLogo = document.createElement("div");
let imgLogo = document.createElement("img");
imgLogo.id = "logo-nav";
imgLogo.setAttribute("src", "./LOgo/logo3.png");
imgLogo.setAttribute("alt", "slika-logo");
divLogo.appendChild(imgLogo);

headerTop.appendChild(divLogo);
export let divLogForm = document.createElement("div");
divLogForm.id = "formLogIn";
divLogForm.classList.add("remove");
document.body.appendChild(divLogForm);
export let logInh2 = document.createElement("h2");
logInh2.innerText = "Uloguj se";
divLogForm.appendChild(logInh2);
let formImg = document.createElement("img");
formImg.classList.add("flom-slika");
formImg.setAttribute("src", "./LOgo/narandzasta1.png");
formImg.setAttribute("alt", "slika-form");
divLogForm.appendChild(formImg);
export let logclose = document.createElement("button");
logclose.classList.add("btnLogoClose");
logclose.innerText = "X";
divLogForm.appendChild(logclose);
export let formLog = document.createElement("form");
formLog.classList.add("formLog");
divLogForm.appendChild(formLog);

let forma2Div = document.createElement("div");
formLog.appendChild(forma2Div);
export let labelForm = document.createElement("label");
labelForm.setAttribute("for", "username");
labelForm.innerText = "Username";
forma2Div.appendChild(labelForm);
export let input1Form = document.createElement("input");
input1Form.id = "inputUsername";
input1Form.setAttribute("name", "username");
input1Form.setAttribute("type", "text");
forma2Div.appendChild(input1Form);

let forma1Div = document.createElement("div");
formLog.appendChild(forma1Div);
export let labe2Form = document.createElement("label");
labe2Form.setAttribute("for", "password");
labe2Form.innerText = "Password";
forma1Div.appendChild(labe2Form);
export let input2Form = document.createElement("input");
input2Form.id = "inputPassword";
input2Form.setAttribute("name", "password");
input2Form.setAttribute("type", "text");
forma1Div.appendChild(input2Form);
export let butLog = document.createElement("button");
butLog.id = "butLog";
butLog.innerText = "uloguj se";
divLogForm.appendChild(butLog);

export let divKorpaBuy = document.createElement("div");
divKorpaBuy.id = "ceoDivKorpa";
document.body.appendChild(divKorpaBuy);

let navHead = document.createElement("nav");
let paragrafKorpa = document.createElement("p");
paragrafKorpa.classList.add("paragrafKorpa");
navHead.appendChild(paragrafKorpa);
navHead.id = "myLinks";
headerTop.appendChild(navHead);
let ulHead = document.createElement("ul");
navHead.appendChild(ulHead);
let li1 = document.createElement("li");
li1.setAttribute("href", "#header");
ulHead.appendChild(li1);
let a1 = document.createElement("a");
a1.classList.add("nav-link");
a1.setAttribute("href", "#header");
a1.innerText = "Home";
li1.appendChild(a1);

let li2 = document.createElement("li");
li2.setAttribute("href", "#about");
ulHead.appendChild(li2);
let a2 = document.createElement("a");
a2.classList.add("nav-link");
a2.setAttribute("href", "#about");
a2.innerText = "About";
li2.appendChild(a2);

let li3 = document.createElement("li");
li3.setAttribute("href", "#products");
ulHead.appendChild(li3);
let a3 = document.createElement("a");
a3.classList.add("nav-link");
a3.setAttribute("href", "#products");
a3.innerText = "Products";
li3.appendChild(a3);

let li4 = document.createElement("li");
li4.setAttribute("href", "#pitanja");
ulHead.appendChild(li4);
let a4 = document.createElement("a");
a4.classList.add("nav-link");
a4.setAttribute("href", "#pitanja");
a4.innerText = "FAQ";
li4.appendChild(a4);

let li5 = document.createElement("li");
li5.setAttribute("href", "#contact");
ulHead.appendChild(li5);
let a5 = document.createElement("a");
a5.classList.add("nav-link");
a5.setAttribute("href", "#contact");
a5.innerText = "Contact";
li5.appendChild(a5);
export let divKorpa1 = document.createElement("div");
divKorpa1.classList.add("divKorpa1");

navHead.appendChild(divKorpa1);
export let dugmeOtvoriKorpu = document.createElement("a");
dugmeOtvoriKorpu.classList.add("add-to-cart");

dugmeOtvoriKorpu.setAttribute("href", "#");
dugmeOtvoriKorpu.innerText = "open";
divKorpa1.appendChild(dugmeOtvoriKorpu);
let a2divKorpa = document.createElement("a");
a2divKorpa.classList.add("cart");
a2divKorpa.setAttribute("href", "#");
export let spanA2Br = document.createElement("span");
spanA2Br.classList.add("spanA2");
divKorpa1.appendChild(spanA2Br);
spanA2Br.innerText = "";
divKorpa1.appendChild(a2divKorpa);

export let secttionSlide = document.createElement("section");
secttionSlide.id = "slider-main";
document.body.appendChild(secttionSlide);
export let divSlider = document.createElement("div");
divSlider.id = "slider";
secttionSlide.appendChild(divSlider);
let sectionAbout = document.createElement("section");
sectionAbout.id = "about";
document.body.appendChild(sectionAbout);
let h2About = document.createElement("h2");
h2About.innerText = "O nama";
sectionAbout.appendChild(h2About);
let aboutMain = document.createElement("div");
aboutMain.id = "aboutMain";
sectionAbout.appendChild(aboutMain);
let slikaAbout = document.createElement("div");
slikaAbout.id = "div-slika-about";
aboutMain.appendChild(slikaAbout);
let imgAbout = document.createElement("img");
imgAbout.setAttribute("src", "./slike about/about1.jpg");
imgAbout.setAttribute("alt", "slika about");
slikaAbout.appendChild(imgAbout);
let aboutContent = document.createElement("div");
aboutContent.id = "about-content";
aboutMain.appendChild(aboutContent);
let abouth3 = document.createElement("h3");
abouth3.innerText =
  " MobilniShop kao OnLine prodavnica uspešno posluje na tržištu Srbije punih 5 godina sa timom ljudi koji nosi iskustvo u prodaji telefona više od jedne decenije.";
aboutContent.appendChild(abouth3);
let aboutP = document.createElement("p");
aboutP.innerText =
  "Kako su proizvođači svakodnevno povećavali broj različitih modela kao i njihovih boja imali smo sve veće iskušenje kako da kupcima ponudimo kompletnu lepezu proizvoda a da ih pri tome ne skladištimo na više mesta.";
aboutContent.appendChild(aboutP);
let aboutP1 = document.createElement("p");
aboutP1.innerText =
  "Kreativnim razmišljanjem došli smo do ideje da budemo u koraku sa vremenom i damo našim kupcima mogućnost kupovine telefona putem interneta i time omogućimo dostupnost svih aparata gde god da se nalaze.";
aboutContent.appendChild(aboutP1);
let aboutP2 = document.createElement("p");
aboutP2.innerText =
  "Kao rezultat toga, 6. maja 2009. godine nastao je naš sajt koji konstantno unapređujemo, kako bi svojim posetiocima pružili što kvalitetniji sadržaj kao i pomoć pri izboru i kupovini telefona i ostale elektronike.";
aboutContent.appendChild(aboutP2);
let aboutP3 = document.createElement("p");
aboutP3.innerText =
  " Do sada smo se dokazali kao lideri u Srbiji na području OnLine prodaje mobilnih telefona i imamo ozbiljne namere da u budućnosti radimo još bolje.";
aboutContent.appendChild(aboutP3);
let sectionProducts = document.createElement("section");
let producth3 = document.createElement("h2");
producth3.classList.add("zamenaH");
sectionProducts.appendChild(producth3);
producth3.innerText = "Brendovi";
sectionProducts.id = "products";
document.body.appendChild(sectionProducts);
const divIzaberiPro = document.createElement("div");
divIzaberiPro.classList.add("divProizvodi");
sectionProducts.appendChild(divIzaberiPro);
export let producth2 = document.createElement("h2");
producth2.innerText = "Brendovi :";
divIzaberiPro.appendChild(producth2);
let divSamsung = document.createElement("div");
divIzaberiPro.appendChild(divSamsung);
export let slikaSamsung = document.createElement("img");
slikaSamsung.setAttribute("alt", "slikaSamsung");
slikaSamsung.setAttribute("src", "./slike about/samsung.png");
divSamsung.appendChild(slikaSamsung);
slikaSamsung.style.height = "9rem";
slikaSamsung.style.width = "8rem";
let divHyuawie = document.createElement("div");
divIzaberiPro.appendChild(divHyuawie);
export let slikaHyuawie = document.createElement("img");
slikaHyuawie.setAttribute("alt", "slikaHyuavei");
slikaHyuawie.setAttribute("src", "slike about/huawei.png");
divHyuawie.appendChild(slikaHyuawie);
let divApple = document.createElement("div");
divIzaberiPro.appendChild(divApple);
export let slikaApple = document.createElement("img");
slikaApple.setAttribute("alt", "slikaApple");
slikaApple.setAttribute("src", "./slike about/apple.png");
divApple.appendChild(slikaApple);
let divXaomi = document.createElement("div");
divIzaberiPro.appendChild(divXaomi);
export let slikaXaomi = document.createElement("img");
slikaXaomi.setAttribute("alt", "slikaXaomi");
slikaXaomi.setAttribute("src", "./slike about/xaomi3.png");
divXaomi.appendChild(slikaXaomi);
// slikaXaomi.style.height ="9rem";
// slikaXaomi.style.width ="15rem";

let wrapercene = document.createElement("div");
wrapercene.classList.add("wrapercene");
sectionProducts.appendChild(wrapercene);
export let aDoDvesta = document.createElement("a");
aDoDvesta.innerText = "cena do 200 €";
wrapercene.appendChild(aDoDvesta);
export let aDoCetristo = document.createElement("a");
aDoCetristo.innerText = "cena do 400 €";
wrapercene.appendChild(aDoCetristo);
export let aDoHiljadu = document.createElement("a");
aDoHiljadu.innerText = "cena do 1000 €";
wrapercene.appendChild(aDoHiljadu);
let popTel = document.createElement("div");
popTel.id = "popTel";
sectionProducts.appendChild(popTel);
let proizvodi = document.createElement("div");
proizvodi.id = "proizvodi";
sectionProducts.appendChild(proizvodi);
let sectionPitanja = document.createElement("section");
sectionPitanja.id = "pitanja";
document.body.appendChild(sectionPitanja);
let pitanjah2 = document.createElement("h2");
pitanjah2.innerText = "Pitanja";
sectionPitanja.appendChild(pitanjah2);
let pitanjaDiv = document.createElement("div");
pitanjaDiv.id = "pitanja-odgovori";
sectionPitanja.appendChild(pitanjaDiv);
let pitanje1 = document.createElement("h5");
pitanje1.innerText = "Da li su Vaši telefoni novi?";
pitanjaDiv.appendChild(pitanje1);
let odgovor1 = document.createElement("p");
odgovor1.innerText = "Svi naši telefoni su novi i nekorišćeni.";
pitanjaDiv.appendChild(odgovor1);
let pitanje2 = document.createElement("h5");
pitanje2.innerText = "Da li su Vaši telefoni originalni?";
pitanjaDiv.appendChild(pitanje2);
let odgovor2 = document.createElement("p");
odgovor2.innerText = "Mi se bavimo prodajom isključivo originalnih telefona.";
pitanjaDiv.appendChild(odgovor2);
let pitanje3 = document.createElement("h5");
pitanje3.innerText = "Odakle su Vaši telefoni?";
pitanjaDiv.appendChild(pitanje3);
let odgovor3 = document.createElement("p");
odgovor3.innerText = "Telefonima se snabdevamo od Evropskih distributera.";
pitanjaDiv.appendChild(odgovor3);
let pitanje4 = document.createElement("h5");
pitanje4.innerText = "Da li vršite dostavu robe u manjim sredinama?";
pitanjaDiv.appendChild(pitanje4);
let odgovor4 = document.createElement("p");
odgovor4.innerText =
  "Vršimo isporuku u svako i najmanje selo ili grad u Srbiji uz pomoć kurirskih službi sa kojima sarađujemo..";
pitanjaDiv.appendChild(odgovor4);
let pitanje5 = document.createElement("h5");
pitanje5.innerText = "Zašto su vam cene tako povoljne";
pitanjaDiv.appendChild(pitanje5);
let odgovor5 = document.createElement("p");
odgovor5.innerText =
  "Trudimo se da izađemo pred kupce sa najboljim cenama. Pogledajte više u kategoriji “O nama";
pitanjaDiv.appendChild(odgovor5);
let pitanje6 = document.createElement("h5");
pitanje6.innerText = "Da li mogu lično da preuzmem telefon??";
pitanjaDiv.appendChild(pitanje6);
let odgovor6 = document.createElement("p");
odgovor6.innerText =
  "Za sada je moguće lično preuzeti aparat u našim servisima u Beogradu u Balkanskoj ulici br. 35 i Novom Sadu u ulici Ilije Ognjanovića br. 4, uz nadoknadu poštarine u iznosu od 250 dinara. Kada se paket šalje na kućnu adresu isporuka je takođe 250 dinara. Poslovanje naša firme je koncipirano na internet prodaji.";
pitanjaDiv.appendChild(odgovor6);
let pitanje7 = document.createElement("h5");
pitanje7.innerText = "Da li vršite isporuku za Crnu Goru?";
pitanjaDiv.appendChild(pitanje7);
let odgovor7 = document.createElement("p");
odgovor7.innerText =
  "Za sada vršimo isporuku samo na teritoriji Srbije, ali nam je u planu da proširimo poslovanje i na bivše Jugoslovenske republike.";
pitanjaDiv.appendChild(odgovor7);
let pitanje8 = document.createElement("h5");
pitanje8.innerText = "Koja je garancija da će telefon biti ispravan?";
pitanjaDiv.appendChild(pitanje8);
let odgovor8 = document.createElement("p");
odgovor8.innerText = "Svaki telefon ima garanciju 2 godine";
pitanjaDiv.appendChild(odgovor8);
let pitanje9 = document.createElement("h5");
pitanje9.innerText = "Da li je svejedno koja je zemlja porekla telefona?";
pitanjaDiv.appendChild(pitanje9);
let odgovor9 = document.createElement("p");
odgovor9.innerText =
  "Poreklo telefona je nebitno kada se radi o originalnim telefonima. U društvu postoji velika zabluda po ovom pitanju. Proizvođači imaju svoje fabrike u mnogim zemljama širom sveta, ali se gotovo uvek matične ploče telefona rade u njihovim maticama, dok se ostali delovi, kao što je ubacivanje maske, displeja, baterije i pakovanje telefona u kutije vrši u zemljama poput Mađarske (Nokia fabrika u Komaronu";
pitanjaDiv.appendChild(odgovor9);
let pitanje10 = document.createElement("h5");
pitanje10.innerText = "Da li može telefon da se kupi na rate?";
pitanjaDiv.appendChild(pitanje10);
let odgovor10 = document.createElement("p");
odgovor10.innerText =
  "Za sada je plaćanje isključivo jednoročno u gotovini , karticom i pay-pal.";
pitanjaDiv.appendChild(odgovor10);

let sectionContact = document.createElement("section");
sectionContact.id = "contact";
document.body.appendChild(sectionContact);
let contacth2 = document.createElement("h2");
contacth2.innerText = "Kontakt";
sectionContact.appendChild(contacth2);
let mapDiv = document.createElement("div");
mapDiv.className = "map";
sectionContact.appendChild(mapDiv);
let iframe = document.createElement("iframe");
iframe.setAttribute(
  "src",
  "https://www.google.com/maps/d/embed?mid=1JCcsGhxH8Hmqa7wUt2r0s9_LVzg&hl=en"
);
iframe.setAttribute("width", "100%");
iframe.setAttribute("height", "350");
mapDiv.appendChild(iframe);
export let allContact = document.createElement("div");
allContact.className = "all-contact";
sectionContact.appendChild(allContact);

let divUnos = document.createElement("div");
divUnos.id = "div-korisnik-unos";
allContact.appendChild(divUnos);
export let contactForm = document.createElement("form");
divUnos.appendChild(contactForm);

export let formLabel = document.createElement("div");
formLabel.classList.add("formLabel");
contactForm.appendChild(formLabel);
export let formDiv1 = document.createElement("div");
contactForm.appendChild(formDiv1);
let label1 = document.createElement("label");
label1.setAttribute("for", "mejl-korisnik");
label1.innerText = "E-mail:";
formLabel.appendChild(label1);
export let input1 = document.createElement("input");
input1.id = "mejlKorisnik";
input1.setAttribute("name", "mejl-korisnik");

input1.setAttribute("placeholder", "Vas email");
formDiv1.appendChild(input1);

export let formLabel1 = document.createElement("div");
formLabel1.classList.add("formLabel1");
contactForm.appendChild(formLabel1);

export let formDiv2 = document.createElement("div");
contactForm.appendChild(formDiv2);
let label2 = document.createElement("label");
label2.setAttribute("for", "tel");
label2.innerText = "Kontakt telefon:";
formLabel1.appendChild(label2);
export let input2 = document.createElement("input");
input2.id = "telKorisnik";
input2.setAttribute("name", "tel");
input2.setAttribute("type", "tel");

input2.setAttribute("placeholder", "+381xxxxxxxxx");
formDiv2.appendChild(input2);

export let formLabel2 = document.createElement("div");
formLabel2.classList.add("formLabel2");
contactForm.appendChild(formLabel2);

let formDiv3 = document.createElement("div");
contactForm.appendChild(formDiv3);
let labe3 = document.createElement("labe");
labe3.style.fontWeight = "bold";
labe3.setAttribute("for", "text-mail");
labe3.innerText = "Postavite pitanje:";
formLabel2.appendChild(labe3);
export let textArea = document.createElement("textarea");
textArea.id = "textKorisnik";
textArea.setAttribute("name", "text-mejl");
textArea.setAttribute("cols", "30");
textArea.setAttribute("spellcheck", "false");
textArea.setAttribute("rows", "10");
textArea.setAttribute("placeholder", "placeholder");
formDiv3.appendChild(textArea);
let formDiv4 = document.createElement("div");
contactForm.appendChild(formDiv4);
export var formbtn = document.createElement("button");
formbtn.classList.add("dugmeKorisnik");
formbtn.setAttribute("type", "submit");
formbtn.innerHTML = "Pošalji";
formDiv4.appendChild(formbtn);

let divContact = document.createElement("div");
divContact.className = "kontakt";
allContact.appendChild(divContact);
let kontakth4 = document.createElement("h4");
kontakth4.innerText = "Naši podaci:";
divContact.appendChild(kontakth4);

let pUlica = document.createElement("p");
pUlica.innerText = "Ulica:";
divContact.appendChild(pUlica);
let aUlica = document.createElement("a");
aUlica.setAttribute(
  "href",
  'https://www.google.rs/maps/place/%D0%9A%D0%B0%D1%80%D0%B0%D1%92%D0%BE%D1%80%D1%92%D0%B5%D0%B2%D0%B0+12,+%D0%91%D0%B5%D0%BE%D0%B3%D1%80%D0%B0%D0%B4+11080/@44.8401311,20.4153869,21z/data=!4m5!3m4!1s0x475a65a79a5cc455:0x61b8ef3eae5f1b76!8m2!3d44.8401594!4d20.4155588">'
);
aUlica.innerText = "Karadjordjeva 12 , Beograd";
pUlica.appendChild(aUlica);
let pUlica1 = document.createElement("p");
pUlica1.innerText = "E-mail:";
divContact.appendChild(pUlica1);
let aUlica1 = document.createElement("a");
aUlica1.setAttribute("href", "mailto:name@rapidtables.com");
aUlica1.innerText = "example@gmail.com";
pUlica1.appendChild(aUlica1);
let pUlica2 = document.createElement("p");
pUlica2.innerText = "Ulica:";
divContact.appendChild(pUlica2);
let aUlica2 = document.createElement("a");
aUlica2.setAttribute("href", "tel:123-456-7890");
aUlica2.innerText = "011555444";
pUlica2.appendChild(aUlica2);
let pUlica3 = document.createElement("p");
pUlica3.innerText = "Skype";
divContact.appendChild(pUlica3);
let aUlica3 = document.createElement("a");
aUlica3.setAttribute("href", "skype:YourSkypeName?call");
aUlica3.innerText = "mobilshop";
pUlica3.appendChild(aUlica3);
let footer = document.createElement("footer");
footer.id = "footer";
document.body.appendChild(footer);
let mainFot = document.createElement("div");
mainFot.id = "footerMain";
footer.appendChild(mainFot);
let fotMain1Div = document.createElement("div");
mainFot.appendChild(fotMain1Div);
let fotH4 = document.createElement("h4");
fotH4.className = "foth";
fotH4.innerText = "Linkovi";
fotH4.id = "Linkovi";
fotMain1Div.appendChild(fotH4);
let fotUl = document.createElement("ul");
fotMain1Div.appendChild(fotUl);
let li6 = document.createElement("li");
li6.classList.add("nav-link");
li6.setAttribute("href", "#header");
li6.innerText = "Home";
fotUl.appendChild(li6);
let li7 = document.createElement("li");
li7.classList.add("nav-link");
li7.setAttribute("href", "#about");
li7.innerText = "About";
fotUl.appendChild(li7);
let li8 = document.createElement("li");
li8.classList.add("nav-link");
li8.setAttribute("href", "#products");
li8.innerText = "Products";
fotUl.appendChild(li8);
let li9 = document.createElement("li");
li9.classList.add("nav-link");
li9.setAttribute("href", "#pitanja");
li9.innerText = "FAQ";
fotUl.appendChild(li9);
let li10 = document.createElement("li");
li10.classList.add("nav-link");
li10.setAttribute("href", "#contact");
li10.innerText = "Contact";
fotUl.appendChild(li10);
let fotMain2Div = document.createElement("div");
fotMain2Div.classList.add("info-fot");
mainFot.appendChild(fotMain2Div);
let fotMain2DivH4 = document.createElement("h4");
fotMain2DivH4.innerText = "Kontakt:";
fotMain2DivH4.classList.add = "foth";
fotMain2Div.appendChild(fotMain2DivH4);
let pfot1 = document.createElement("p");
pfot1.innerText = "E-mail:";
fotMain2Div.appendChild(pfot1);
let afot1 = document.createElement("a");
afot1.setAttribute("href", "mailto:name@rapidtables.com");
afot1.innerText = "example@gmail.com";
pfot1.appendChild(afot1);
let pfot2 = document.createElement("p");
pfot2.innerText = "E-mail:";
fotMain2Div.appendChild(pfot2);
let afot2 = document.createElement("a");
afot2.setAttribute("href", "tel:123-456-7890");
afot2.innerText = "011555444";
pfot2.appendChild(afot2);
let pfot3 = document.createElement("p");
pfot3.innerText = "Skype:";
fotMain2Div.appendChild(pfot3);
let afot3 = document.createElement("a");
afot3.setAttribute("href", "skype:YourSkypeName?call");
afot3.innerText = "mobilshop";
pfot3.appendChild(afot3);
let fotMain3Div = document.createElement("div");
fotMain3Div.classList.add("font-footer");
let facebook = document.createElement("p");
facebook.classList.add("facebook");
fotMain3Div.appendChild(facebook);
let instagram = document.createElement("p");
instagram.classList.add("instagram");
fotMain3Div.appendChild(instagram);
let google = document.createElement("p");
google.classList.add("google");
fotMain3Div.appendChild(google);
mainFot.appendChild(fotMain3Div);
let fotMain3DivH4 = document.createElement("h4");
fotMain3DivH4.innerText = "Pratite nas";
fotMain3DivH4.classList.add = "foth";
fotMain3Div.appendChild(fotMain3DivH4);
let brendoviDiv = document.createElement("div");
brendoviDiv.classList.add("brendovi");
footer.appendChild(brendoviDiv);
let brend1 = document.createElement("img");
brend1.setAttribute("src", "slike about/htc.png");
let brend2 = document.createElement("img");
brend2.setAttribute("src", "slike about/samsung.png");
let brend3 = document.createElement("img");
brend3.setAttribute("src", "slike about/huawei.png");
let brend4 = document.createElement("img");
brend4.setAttribute("src", "slike about/lg.png");
let brend5 = document.createElement("img");
brend5.setAttribute("src", "slike about/motorola.png");
brendoviDiv.appendChild(brend1);
brendoviDiv.appendChild(brend2);
brendoviDiv.appendChild(brend3);
brendoviDiv.appendChild(brend4);
brendoviDiv.appendChild(brend5);
let copyrightsDiv = document.createElement("div");
copyrightsDiv.classList.add("copyDiv");
footer.appendChild(copyrightsDiv);
let copyP = document.createElement("p");
copyP.classList.add("copy");
copyP.innerText = "Projektni zadatak Siniša Zlatković 2020";
copyrightsDiv.appendChild(copyP);
